version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: lynk_pg
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: lynkdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d lynkdb"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pg_data:
